artifact_uri: file:C:\Users\DESKTOP\Downloads\fin\qlib\examples\benchmarks\Alpha158\mlruns_alpha158/912768084596037704/05d1deca2bbd44bd8c393561b8e2c965/artifacts
end_time: 1770537116019
entry_point_name: ''
experiment_id: '912768084596037704'
lifecycle_stage: active
run_id: 05d1deca2bbd44bd8c393561b8e2c965
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1770537055879
status: 3
tags: []
user_id: DESKTOP
